services:
  flask:
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: "${COMMIT_SHA:-HEAD}"
    depends_on:
      mysql:
        condition: service_started
    environment:
      DB_HOST: mysql
      DB_PASS: "${DB_PASS}"
      DB_USERNAME: "${DB_USERNAME}"
      JWT_TOKEN: "${JWT_TOKEN}"
    image: manquintero/academy-sre-bootcamp-manuel-quintero:latest
    networks:
      default: null
    ports:
    - target: 8000
      published: 8000
    volumes:
    - type: bind
      source: ./python
      target: /app
      bind:
        create_host_path: true
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
    networks:
      default: null
    ports:
    - target: 3306
      published: 3306
    volumes:
    - type: volume
      source: mysql_data
      target: /var/lib/mysql
      volume: {}
networks:
  default:
    name: sre-bootcamp-capstone-project_default
volumes:
  mysql_data:
    name: sre-bootcamp-capstone-project_mysql_data