services:
  api:
    build:
      context: .
    ports:
    - published: 8000
      target: 8000
    volumes:
    - .:/app:rw
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASS: "${DB_PASS}"
      JWT_TOKEN: "${JWT_TOKEN}"
version: '3.9'
