#!/usr/bin/python3
""" This Module contains Test cases associated to Login actions """

import unittest

from methods import Token, Restricted

TOKEN = 'Bearer: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4ifQ' \
        '.BmcZ8aB5j8wLSK8CqdDwkGxZfFwM1X1gfAIN7cXOx9w '


class TokenTestCase(unittest.TestCase):
    """ Test cases related to Token """

    def setUp(self):
        self.convert = Token()

    def test_generate_token(self):
        """ Assert that the correct TOKEN is generated by a known source of roles """
        query = None
        self.assertEqual(TOKEN, self.convert.generate_token('admin', 'secret', query))


class RestrictedTestCase(unittest.TestCase):
    """ Test cases related to Restricted """

    def setUp(self):
        self.validate = Restricted()

    def test_access_data(self):
        """ Asserts a role have privilege access granted """
        self.assertTrue(self.validate.access_data(TOKEN))

    def test_access_data_corrupt(self):
        """ Changing one character returns a False """
        corrupt_token = TOKEN[0:-1] + 'a'
        self.assertFalse(self.validate.access_data(corrupt_token))

    def test_access_data_invalid_schema(self):
        """ Not sending the flag 'Bearer' sends an Unauthorized """
        invalid_schema_token = TOKEN.replace('Bearer:', 'Token:')
        self.assertFalse(self.validate.access_data(invalid_schema_token))

    def test_access_data_no_bearer(self):
        """ Not sending the flag 'Bearer' sends an Unauthorized """
        self.assertFalse(self.validate.access_data('fyJh.eyb2'))


if __name__ == '__main__':  # pragma: no cover
    unittest.main()
