name: 'Terraform'
'on':
  push:
    branches:
      - infra
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: |
          terraform -chdir=infrastructure/global/s3 fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=infrastructure/global/s3 init
      
      - name: Terraform Validate
        id: validate
        run: |
          terraform -chdir=infrastructure/global/s3 validate -no-color